<?xml version="1.0" encoding="utf-8"?>

<Project>
    <PropertyGroup>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    </PropertyGroup>
</Project>